/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.codething;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TrackerAppTest {
    @Test void appHasThnigs() {
        TrackerApp classUnderTest = new TrackerApp();

    }

    /**
     * write a java test that can take this "mktx:100,cflt:200,apple:150,alpha:23,drill:78"
     */
    @Test void shouldProcessThis() {

        final var payload = "mktx:100,cflt:200,apple:150,alpha:23,drill:78";

        int lowest = 78;

        Assertions.assertEquals(lowest, 78);



    }



}
