/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.codething;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.junit.jupiter.api.Assertions.*;
import org.hamcrest.MatcherAssert.assertThat;
import org.hamcrest.Matchers.*;

class TrackerAppTest {
    @Test void appHasThings() {
        TrackerApp classUnderTest = new TrackerApp();
        var expectedValue = "expected";
        var actualValue = "expected";

        // Using Hamcrest matchers for assertions
        assertThat(actualValue, is(expectedValue));
    }

//
//    IGNORE
//
//    /**
//     * write a java test that can take this "mktx:100,cflt:200,apple:150,alpha:23,drill:78"
//     */
//    @Test void shouldProcessThis() {
//
//        final var payload = "mktx:100,cflt:200,apple:150,alpha:23,drill:78";
//
//        int lowest = 78;
//
//        Assertions.assertEquals(lowest, 78);
//
//
//
//    }



}
